== 構文

この章では Crystal の構文について説明します。

Crystal の構文は Ruby によく似ているため、Ruby と比較しながら説明することが多くなります。Ruby の構文については以下の資料などを参考にしてください。

* https://docs.ruby-lang.org/ja/latest/doc/index.html[オブジェクト指向スクリプト言語 Ruby リファレンスマニュアル]

また、この章の内容は Crystal 公式ドキュメントの https://crystal-lang.org/docs/syntax_and_semantics/[Syntax and Semantics] を大きく参考にしています。

=== コメント

コメントは `#` から始めます。

[source,crystal]
----
include::./examples/comment.cr[]
----

NOTE: Ruby にある `=begin` と `=end` による複数行のコメントは Crystal はサポートしていないので注意してください。

=== リテラル

==== `nil`

何も無い値を意味する `nil` というリテラルがあります。

これは Java の `null` や Python の `Nothing` に相当します。

[source,crystal]
----
include::./examples/nil.cr[]
----

Crystal では `nil` はかなり特殊な値で、 `nil` を含む値を便利に扱うための構文がいくつか存在します。

==== 論理値

論理値は `Bool` 型の値で、 `true` と `false` です。

[source,crystal]
----
include::./examples/bool.cr[]
----

==== 数値リテラル

数値リテラルも Ruby や多くの言語と同じような構文になっています。

[source,crystal]
----
include::./examples/number.cr[]
----

いくつか特殊な点があるとすれば、数値リテラルの区切りに `_` を使えるところと、 `i64` や `f32` などの接尾辞を付けることで数値リテラルの型を明示できるところがあります。

例えば、 `100i64` は `Int64` 型（64ビットの符号付き整数型）の `100` になります。
同様に `100u64` は `UInt64` 型（64ビットの符号なし整数型）の `100` になります。

末尾に何も付いていない場合、整数リテラルなら `Int32` 型、小数点や指数があれば `Float64` 型になります。

.数値リテラルの接尾辞の種類
[cols="2*1,3",options=header,width=70%]
|===
|接尾辞|型|説明

| `i8`   | `Int8`   | 8ビットの符号付き整数型
| `i16`  | `Int16`  | 16ビットの符号付き整数型
| `i32`  | `Int32`  | 32ビットの符号付き整数型
| `i64`  | `Int64`  | 64ビットの符号付き整数型
| `i128` | `Int128` | 128ビットの符号付き整数型

| `u8`   | `UInt8`   | 8ビットの符号なし整数型
| `u16`  | `UInt16`  | 16ビットの符号なし整数型
| `u32`  | `UInt32`  | 32ビットの符号なし整数型
| `u64`  | `UInt64`  | 64ビットの符号なし整数型
| `u128` | `UInt128` | 128ビットの符号なし整数型

| `f32` | `Float32` | 32ビットの浮動小数点型
| `f64` | `Float64` | 64ビットの浮動小数点型
|===

==== シンボル

シンボルは変更できない文字列のようなもので、Ruby と大体同じ構文です。

`:` から始まる単語はシンボルになります。

NOTE: Crystal では Ruby ほどシンボルを使いません。なぜならば `String#intern` や `String#to_symbol` などのメソッドが無く、プログラム中で動的にシンボルを生成することが不可能だからです。また、シンボルリテラルの中に `#{}` を含めて実行時にシンボルの値を決めることもできません。

[source,crystal]
----
include::./examples/symbol.cr[]
----

NOTE: Crystal は Ruby にある `%s` 形式のシンボルリテラルをサポートしていません。

==== 文字と文字列

NOTE: Crystal は型のある言語なので、Ruby とは異なり文字と文字列を区別します。

文字リテラルは `'` で囲まれた文字です。

[source,crystal]
----
include::./examples/char.cr[]
----

当然ですが、文字リテラルなので `'` の中に二文字以上の文字を含むと構文エラーになります。

文字列リテラルは `"` で囲む形式や `%` から始まる形式、ヒアドキュメントという3つの形式が存在します。

[source,crystal]
----
include::./examples/string.cr[]
----

==== 配列

配列も Ruby と同じように、
