== Web 開発


この章では、 Crystal を用いて Web 開発を行う方法について解説します。 +
本サンプルで使用する Crystal のバージョンは「0.24.1」で確認しています。

=== Crystal の Web フレームワーク

Crystal で現在最も活発に開発されている Web フレームワークが Kemal です。 +
Ruby でいうところの Sinatra に似た設計思想で作られており、シンプルな実装で Web アプリを作成することが出来ます。 +
本書では主に Kemal を用いて簡単な Web アプリを作成しながら Web 開発の方法を解説していきます。

* URL http://kemalcr.com/  
* GitHub https://github.com/kemalcr/kemal 

また Kemal 以外の主なフレームワークとして以下のものがあります。

* Amber https://www.amberframework.org

フルスタックの Web フレームワークです。 +
様々なコードジェネレータや、 O/RM を備えています。 Rails 的な規約重視のフレームワークです。 +

=== Kemal による Web 開発

それでは本章から Kemal による Web 開発を、サンプルを交えながら説明します。
また本サンプルに使用する Kemal のバージョンは「0.22.0」を想定しています。

==== Kemal インストール

適当な作業用のディレクトリ以下で、以下のコードを実行してみます。ディレクトリが作成され幾つかのファイルがひな形から作成されます。 +
本稿ではサンプルアプリを kemal-sample として進めます。

....
crystal init app kemal-sample
cd kemal-sample
....

shard.yml ファイルに以下の内容を追記します。

[source,yaml]
----
include::./projects/kemal-sample/shard.yml[lines=11..14]
----

以下のコマンドを実行することで Kemal 本体をインストールすることが出来ます。

....
shards install
....

==== Kemal FirstStep

インストールまで問題なく動かせたら続いて簡単なサンプルを作成してみましょう。 +
カレントの src ディレクトリ以下の「 kemal-sample.cr 」に以下の追記を行います。

まず行頭に以下の行を足します。

....

require "kemal"
....

続いて「 module Kemal::Sample 」内に以下の内容を追記します。

[source,crystal]
----
include::./projects/kemal-sample/src/kemal-sample.cr[tags=hello]
----

末尾の行に以下の内容を追記します。

....
Kemal.run
....

画面側の処理を作成します。 +
src 以下に view ディレクトリを作成し、以下の hello.ecr ファイルを view ディレクトリ内に作成します。

[source,html]
----
include::./projects/kemal-sample/src/views/hello.ecr[]
----

Kemal の基本的な使い方として、 REST の動詞 GET POST PUT DELETE を以下の形で記述します。

....
get "/path" do |env|
  # 処理
end

post "/path" do |env|
  # 処理
end
....

詳しい内容については後述します。
先ずは記述したら、以下のコマンドでビルド、実行します。

....
crystal build src/kemal-sample.cr
./kemal-sample
....

ブラウザで「http://localhost:3000/」でアクセスします。 +
「 Hello World 」と表示されていれば問題ありません。

==== DB と連動する

通常、 Web アプリでは DB が必須です。 Kemal で作ったアプリから DB にアクセスすることも可能です。 +
ライブラリを使用することで PostgreSQL か、もしくは MySQL を使用することが出来ます。 +
今回は PostgreSQL を使用します。

.テーブル名 articles
|============
|カラム名|型
|id     |serial
|title  |text
|content|text
|============

DB を作成します。
....
createdb kemal_sample_development -O your_owner
....

DDL を作成しロードします。

[source,sql]
----
include::./projects/kemal-sample/sql/create_articles.sql[]
----

....
psql -U your_owner -d kemal_sample_development -f sql/create_articles.sql
....

作成した後、 shard.yml ファイルに以下の内容を追記します。

[source,yaml]
----
include::./projects/kemal-sample/shard.yml[lines=11..18]
----

編集後、以下のコマンドを実行します。

....
shards install
....

==== 投稿一覧ページの編集

これからいよいよ Web アプリらしく記事の一覧ページと詳細ページ、新規投稿ページをそれぞれ作成していきます。 +
まず全ページで共通で使用するテンプレートは別に作成します。 +
テンプレートヘッダに新規投稿ページと投稿リストページヘのリンクを表示し、ページ内に各ページのコンテンツを表示するように修正していきます。

==== レイアウトページの作成

まずひな形のページを application.ecr という名前で作成します。

[source,html]
----
include::./projects/kemal-sample/src/views/application.ecr[]
----

本サンプルでは BootStrap を使用します。 +
CDN を使用しますので特にダウンロード不要ですが、ダウンロードする場合は別途「 http://getbootstrap.com/ 」から必要なファイルをダウンロードし、プロジェクトカレントの /public 以下に配置してください。

==== CSS の作成

ページ修飾用の CSS を作成します。本サンプルでは rails tutorial をそのまま参考にします。

[source,css]
----
include::./projects/kemal-sample/public/css/custom.css[]
----

==== 一覧ページの作成

記事一覧ページを以下の内容で作成します。

[source,html]
----
include::./projects/kemal-sample/src/views/index.ecr[]
----

==== 新規投稿ページ

記事投稿用のページを新規作成します。

以下のファイルを追加します。

[source,html]
----
include::./projects/kemal-sample/src/views/articles/new.ecr[]
----

==== 詳細ページ

一覧ページから記事タイトルをクリックした時に遷移する詳細ページを作成します。

[source,html]
----
include::./projects/kemal-sample/src/views/articles/show.ecr[]
----

==== Kemal プログラム改修

kemal-sample.cr を以下の内容で修正します。

行頭を以下の内容に修正します。

....
require "kemal"
require "db"
require "pg"
....

続いて「 module Kemal::Sample 」内に以下の内容を追記します。

[source,crystal]
----
include::./projects/kemal-sample/src/kemal-sample.cr[tags=main]
----

修正は以上です。次項から処理について解説します。

==== クエリ

まずクエリは以下のように記述します。  

[source,crystal]
----
include::./projects/kemal-sample/src/kemal-sample.cr[tags=query]
----

query メソッドに SQL クエリを記述し、ループ内で結果を格納していきます。 +
1件だけ取得したい場合は query_one もしくは `query_one?` を使います。後者は1件もデータが無い場合がありうる場合に使います。  

....
  sql = "select id, title, body from articles where id = $1::int8"
  article["id"], article["title"], article["body"] = 
    db.query_one(sql, params, as: {Int32, String, String})
....

query_one の戻り値は、 as で指定した型の Touple になります。  

....
render "src/views/articles/show.ecr", "src/views/application.ecr"
....

の形式で ecr ファイルをレンダリングすることで、 Rails のようにファイルを入れ子の形で描画することが出来ます。

Web アプリ再起動後に http://localhost:3000/ にアクセスすると、まだ記事が投稿されていないので空欄になっています。 +
http://localhost:3000/articles/new にアクセスすると、タイトルと本文を入力する画面が表示されており、入力後に一覧に遷移すると成功です。 +
記事タイトルをクリックすると詳細画面に遷移すると成功です。
